src/Entity/Cv.php
<?php

namespace App\Entity;

use App\Repository\CvRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CvRepository::class)
 */
class Cv
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_create;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_update;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(\DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(\DateTimeInterface $date_update): self
    {
        $this->date_update = $date_update;

        return $this;
    }
    public function __toString(){
        return $this->getContent();
    }
}

src/Form/CvType.php
<?php

namespace App\Form;

use App\Entity\Cv;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CvType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('content')
            ->add('date_create')
            ->add('date_update')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cv::class,
        ]);
    }
}

src/Controller/CvController.php
<?php

namespace App\Controller;

use App\Entity\Cv;
use App\Form\CvType;
use App\Repository\CvRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/cv')]
class CvController extends AbstractController
{
    #[Route('/', name: 'cv_index', methods: ['GET'])]
    public function index(CvRepository $cvRepository): Response
    {
        return $this->render('cv/index.html.twig', [
            'cvs' => $cvRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'cv_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $cv = new Cv();
        $form = $this->createForm(CvType::class, $cv);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($cv);
            $entityManager->flush();

            return $this->redirectToRoute('cv_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cv/new.html.twig', [
            'cv' => $cv,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'cv_show', methods: ['GET'])]
    public function show(Cv $cv): Response
    {
        return $this->render('cv/show.html.twig', [
            'cv' => $cv,
        ]);
    }

    #[Route('/{id}/edit', name: 'cv_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cv $cv, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CvType::class, $cv);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('cv_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cv/edit.html.twig', [
            'cv' => $cv,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'cv_delete', methods: ['POST'])]
    public function delete(Request $request, Cv $cv, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cv->getId(), $request->request->get('_token'))) {
            $entityManager->remove($cv);
            $entityManager->flush();
        }

        return $this->redirectToRoute('cv_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cv/_delete_form.html.twig
<form method="post" action="{{ path('cv_delete', {'id': cv.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cv.id) }}">
    <button class="btn">Delete</button>
</form>

templates/cv/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/cv/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cv{% endblock %}

{% block body %}
    <h1>Edit Cv</h1>

    {{ include('cv/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('cv_index') }}">back to list</a>

    {{ include('cv/_delete_form.html.twig') }}
{% endblock %}

templates/cv/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cv index{% endblock %}

{% block body %}
    <h1>Cv index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Content</th>
                <th>Date_create</th>
                <th>Date_update</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cv in cvs %}
            <tr>
                <td>{{ cv.id }}</td>
                <td>{{ cv.name }}</td>
                <td>{{ cv.content }}</td>
                <td>{{ cv.dateCreate ? cv.dateCreate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ cv.dateUpdate ? cv.dateUpdate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('cv_show', {'id': cv.id}) }}">show</a>
                    <a href="{{ path('cv_edit', {'id': cv.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('cv_new') }}">Create new</a>
{% endblock %}

templates/cv/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cv{% endblock %}

{% block body %}
    <h1>Create new Cv</h1>

    {{ include('cv/_form.html.twig') }}

    <a href="{{ path('cv_index') }}">back to list</a>
{% endblock %}

templates/cv/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cv{% endblock %}

{% block body %}
    <h1>Cv</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cv.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ cv.name }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ cv.content }}</td>
            </tr>
            <tr>
                <th>Date_create</th>
                <td>{{ cv.dateCreate ? cv.dateCreate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_update</th>
                <td>{{ cv.dateUpdate ? cv.dateUpdate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('cv_index') }}">back to list</a>

    <a href="{{ path('cv_edit', {'id': cv.id}) }}">edit</a>

    {{ include('cv/_delete_form.html.twig') }}
{% endblock %}